### ISSUE TITLE
Instructions insufficient for setting up development environment

### ISSUE THREAD

**Issue by MidhunSureshR** [aswinshenoy/BayJDO#16]
The instructions provided in the README do not satisfactorily explain how to locally run this web-app.  It fails to describe the necessary directory structure that is needed for docker-compose (as mandated by the example **docker-compose.yml**) and furthermore it fails to warn that the peerjs-server host/port hard-coded in the client ([object prodConfig in hooks/userPeer.js](https://github.com/aswinshenoy/BayJDO/blob/22910a2c10c0c67c660ffe4e5df2844fb93e2acf/hooks/usePeer.js#L7)) do not match with the ones specified in the example docker-compose.yml.

Excellent work on the project by the way. 👍

**Comment by aswinshenoy** [comment]
Hey, thank you for contributing to BayJDO! 

> peerjs-server host/port hard-coded in the client

Yes, I left it on purpose with the current production configuration so that I could just build the repo without passing any environment variables. But said that, it would be a good practice if we make it accept an environment variable else fallback to a default (which matches local). 
However, as you can see in #5, we are in need to replace PeerJS itself for stability and functionality improvements, so I went lazy and didn't make the PeerJS code more flexible. Thank you for helping out.

> fails to describe the necessary directory structure that is needed for docker-compose
 
Sorry to have mislead you, and thanks again for helping out others.


Looking forward to more contributions from you 👍
